version: "3.0"
services:
    nodesanthiya:
            build:
                context: ./app
            ports:
                - "5000:5000"
    nginxsan:
            restart: always
            build:
                context: ./nginx
            ports:
                - "80:80"
